# Generated by Django 4.1.3 on 2022-11-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_lyrics_song_song_artiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='Song',
        ),
    ]
